### ISSUE TITLE
Uncaught ParseException in Readability.php

### ISSUE THREAD

**Issue by noctux** [Art4/full-text-rss#5]
Hey,

thank you for maintaining this fork of the software and bringing it up to speed with php8.

However, I've noticed two small glitches with this version that did not happen with the original upstream (under php7).

The first issue is an uncaugt ParseException from Readability.php, the second one are type errors in Readability (which I will report as a second bug).

Concerning the ParseException:

When fetching certain feeds, Readability throws an unhandled ParseException (Linebreaks manually inserted for better readability):

```
Fatal error: Uncaught fivefilters\Readability\ParseException: Could not parse text. in /usr/share/webapps/fulltextrss/libraries/fivefilters/readability.php/src/Readability.php:240
Stack trace:
	#0 /usr/share/webapps/fulltextrss/libraries/content-extractor/ContentExtractor.php(219): fivefilters\Readability\Readability->parse()
	#1 /usr/share/webapps/fulltextrss/makefulltextfeed.php(796): ContentExtractor->process()
	#2 {main} thrown in /usr/share/webapps/fulltextrss/libraries/fivefilters/readability.php/src/Readability.php on line 240
```

Manual bisecting on the feed shows that one instance where this happens in when readability tries to extract content from a youtube-video. Here is a minimal reproducer:

```xml
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
	<title>Testfeed</title><link>https://example.org</link><description>Exemplary RSS Feed</description>
	<item>
		<title>Exemplary Youtube Video</title>
		<link>https://www.youtube.com/watch?v=aqz-KE-bpKQ</link>
	</item>
</channel>
</rss>
```

My amateurish attempt at fixing this would be:

```diff
diff --git a/libraries/content-extractor/ContentExtractor.php b/libraries/content-extractor/ContentExtractor.php
index 921d45b..4da0815 100644
--- a/libraries/content-extractor/ContentExtractor.php
+++ b/libraries/content-extractor/ContentExtractor.php
@@ -216,7 +216,11 @@ class ContentExtractor
                        'OriginalURL' => $url,
                        'Parser' => $_parser,
                ]));
-               $this->readability->parse($html);
+               try {
+                       $this->readability->parse($html);
+               } catch (Exception $e) {
+                       return false;
+               }
 
                // we use xpath to find elements in the given HTML document
                // see http://en.wikipedia.org/wiki/XPath_1.0
@@ -956,4 +960,4 @@ class ContentExtractor
        public function getNextPageUrl() {
                return $this->nextPageUrl;
        }
-}
\ No newline at end of file
+}
diff --git a/makefulltextfeed.php b/makefulltextfeed.php
index 54d43df..bb3f991 100644
--- a/makefulltextfeed.php
+++ b/makefulltextfeed.php
@@ -807,7 +807,7 @@ foreach ($items as $key => $item) {
                                        continue; // skip this feed item entry
                                }
                        }
-                       $base_url = get_base_url($readability->getDOMDocument(), $effective_url);
+                       $base_url = ($extract_result) ? get_base_url($readability->getDOMDocument(), $effective_url) : null;
                        if (!$base_url) $base_url = $effective_url;
                        $content_block = ($extract_result) ? $extractor->getContent() : null;
                        $extracted_title = ($extract_result) ? $extractor->getTitle() : '';
@@ -1637,4 +1637,4 @@ function debug($msg) {
                ob_flush();
                flush();
        }
-}
\ No newline at end of file
+}
```

This seems to work for my minimal reproducer above. But I don't know whether this is particularly sane :)

Further information on my setup (hopefully should not matter too much):
- php 8.1.14 (ArchLinux's php-legacy package)
- fulltextrss runs under php-fpm as an fcgi-application

Thanks again for maintaining full-text-rss and for reading this far
	Simon

**Comment by Art4** [comment]
Thank you for reporting this issue.

> When fetching certain feeds, Readability throws an unhandled ParseException (Linebreaks manually inserted for better readability):

I can not reproduce this issue with some test feeds. Could you please provide an url where I can reproduce the issue?
